const escapePdf = (text: string) => text.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)');
const escapeXml = (s: string) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

/** Builds a tiny, valid PDF in the browser so mock files can actually be previewed */
function buildPdfBlob(title: string, lines: string[]): Blob {
  const allLines = [title, '', ...lines, '', 'Generated by SE Operations Portal (mock attachment)'];
  const content = allLines
    .map((line, i) => `BT /F1 ${i === 0 ? 16 : 11} Tf 72 ${740 - i * 22} Td (${escapePdf(line)}) Tj ET`)
    .join('\n');
  const objects = [
    '1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n',
    '2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n',
    '3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>\nendobj\n',
    '4 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n',
    `5 0 obj\n<< /Length ${content.length} >>\nstream\n${content}\nendstream\nendobj\n`,
  ];
  let pdf = '%PDF-1.4\n';
  const offsets: number[] = [];
  for (const obj of objects) { offsets.push(pdf.length); pdf += obj; }
  const xrefStart = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (const off of offsets) pdf += `${String(off).padStart(10, '0')} 00000 n \n`;
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF`;
  return new Blob([pdf], { type: 'application/pdf' });
}

function buildSvgBlob(title: string, lines: string[]): Blob {
  const height = 140 + lines.length * 26;
  const texts = [`<text x="40" y="60" font-size="20" font-weight="bold">${escapeXml(title)}</text>`]
    .concat(lines.map((l, i) => `<text x="40" y="${100 + i * 26}" font-size="14">${escapeXml(l)}</text>`))
    .join('\n  ');
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="600" height="${height}" viewBox="0 0 600 ${height}">\n  <rect width="100%" height="100%" fill="#f8fafc"/>\n  ${texts}\n</svg>`;
  return new Blob([svg], { type: 'image/svg+xml' });
}

export function openMockAttachment(fileName: string, title: string, lines: string[]) {
  const lower = fileName.toLowerCase();
  let blob: Blob;
  if (lower.endsWith('.pdf')) blob = buildPdfBlob(title, lines);
  else if (lower.endsWith('.png') || lower.endsWith('.jpg') || lower.endsWith('.jpeg') || lower.endsWith('.svg')) blob = buildSvgBlob(title, lines);
  else blob = new Blob([[title, ...lines].join('\n')], { type: 'text/plain' });

  const url = URL.createObjectURL(blob);
  window.open(url, '_blank');
  setTimeout(() => URL.revokeObjectURL(url), 60000);
}